### ISSUE TITLE
Error: not working

### ISSUE THREAD

**Issue by 41y08h** [Andrey1994/screen_recorder_sdk#1]
Traceback (most recent call last):
  File "d:\Documents\Programming\PROJECTS\scr_cap.py", line 28, in <module>
    main ()
  File "d:\Documents\Programming\PROJECTS\scr_cap.py", line 10, in main
    pid = int (sys.argv[1])
IndexError: list index out of range

**Comment by Andrey1994** [comment]
In example from readme one argument is required - pid. You have to provide pid of process to capture or 0 to capture fullscreen

**Comment by varchasa** [comment]
Could you please give an example of an argument?

**Comment by Andrey1994** [comment]
as I wrote 0 for full screen capture, pid of the process to capture only single process
