### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Zol1d** [Andrey1994/screen_recorder_sdk#11]
Output:
```
[2020-10-20 22:03:13.238] [recordLogger] [info] Created d3d11 device from 0
[2020-10-20 22:03:13.238] [recordLogger] [info] found 3 displays
[2020-10-20 22:03:13.238] [recordLogger] [error] desktopdiplication is unsupported on current desktop mode
```
I have 3 monitors, but I also tried it with one, and it still didn't work.

**Comment by Andrey1994** [comment]
it looks like this error code DXGI_ERROR_UNSUPPORTED  from microsoft api.
https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutput1-duplicateoutput

from their docs: 
"DXGI_ERROR_UNSUPPORTED if the created IDXGIOutputDuplication interface does not support the current desktop mode or scenario. For example, 8bpp and non-DWM desktop modes are not supported. If DuplicateOutput fails with DXGI_ERROR_UNSUPPORTED, the application can wait for system notification of desktop switches and mode changes and then call DuplicateOutput again after such a notification occurs. For more information, refer to EVENT_SYSTEM_DESKTOPSWITCH and mode change notification (WM_DISPLAYCHANGE).
"

**Comment by Andrey1994** [comment]
From https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nn-dxgi1_2-idxgioutputduplication 

"
A collaboration application can use IDXGIOutputDuplication to access the desktop image. IDXGIOutputDuplication is supported in Desktop Window Manager (DWM) on non-8bpp DirectX full-screen modes and non-8bpp OpenGL full-screen modes. 16-bit or 32-bit GDI non-DWM desktop modes are not supported.
"

**Comment by Andrey1994** [comment]
Try to determine these params for your system.
Also which OS version do you use?

**Comment by Zol1d** [comment]
Windows 10, and I don't know why but OBS studio doesn't seem to work for me also. Is there any way I could solve this?

**Comment by Andrey1994** [comment]
Check these display params to see if desktop duplication supported or not. Also, I think its possible to change them.

Idk how to check or change them. You will need to google it

**Comment by Zol1d** [comment]
I have the displays on extended mode, but I can set them to duplicate.

When I duplicate my other 2 displays its says the same thing except 2 displays found.

But this should work on other Win 10 pcs with one display right?

**Comment by Andrey1994** [comment]
No, modes here means not extended/duplicated

**Comment by Andrey1994** [comment]
They are talking about bits per pixel and DWM enabled/disabled

**Comment by Andrey1994** [comment]
Read my first comment in this issue

**Comment by Zol1d** [comment]
Ok, I tested it on a different pc, it worked, so im not going to bother solving it anymore.
