### ISSUE TITLE
Unable to get things working

### ISSUE THREAD

**Issue by toxicrecker** [Andrey1994/screen_recorder_sdk#13]
Part of Code -
```
screen_recorder.enable_dev_log()
params = screen_recorder.RecorderParams()
screen_recorder.init_resources(params)
```

Output (as soon as i run the code) -
```
[2020-11-09 16:22:46.415] [recordLogger] [info] Created d3d11 device from 0
[2020-11-09 16:22:46.415] [recordLogger] [info] found 1 displays
[2020-11-09 16:22:46.418] [recordLogger] [error] invalid arg to create desktopdiplication
[2020-11-09 16:22:46.418] [recordLogger] [trace] stop video recording is called
[2020-11-09 16:22:48.433] [recordLogger] [trace] wait res for stop video is false
```

**Comment by Andrey1994** [comment]
could you share full code which you run?

**Comment by Andrey1994** [comment]
https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutput1-duplicateoutput

this message means this error code:

E_INVALIDARG for one of the following reasons:
* The specified device (pDevice) is invalid, was not created on the correct adapter, or was not created from IDXGIFactory1 (or a later version of a DXGI factory interface that inherits from IDXGIFactory1).
* The calling application is already duplicating this desktop output.

Are you sure that second is not a case?

**Comment by toxicrecker** [comment]
nevermind, i fixed it, it was because i was using [d3dshot](https://github.com/SerpentAI/D3DShot) library as well, and for some reason i can't use both of the libs together, but no problem i can get things working with this lib too

**Comment by Andrey1994** [comment]
Because of this "The calling application is already duplicating this desktop output." I suppose, maybe you can use both libs at the same time if you split them by two different processes using multiprocessing or subprocess

**Comment by toxicrecker** [comment]
Oh okay thanks for the information but I don't need to use both, i was using it just for screenshots but this lib can do it as well so no problem
