### ISSUE TITLE
Processor Consumption [Too High]

### ISSUE THREAD

**Issue by hash3liZer** [Andrey1994/screen_recorder_sdk#18]
I was testing on a virtual machine without a GPU and to my surprise the processor consumption of it is too high and slowing down the other processes. Is there any way to make it consume less power?

**Comment by Andrey1994** [comment]
Set lower bitrate, maybe it will help
Video encoding is computationally heavy operation...
You can also change the encoder but that will require to rebuild c++ code

**Comment by hash3liZer** [comment]
Hey, @Andrey1994 , i am already on a relatively lower bitrate and can't go any further down. Can you just point to the code block in your package where the encoder is specified. I can't seem to find it.

**Comment by Andrey1994** [comment]
you can change this line https://github.com/Andrey1994/screen_recorder_sdk/blob/master/src/ScreenRecorder/inc/MFEncoder.h#L37 
if it does the trick, maybe it makes sense to make it configurable from python code(user api), PR for that will be welcome

I believe here all possible options are listed https://docs.microsoft.com/en-us/windows/win32/medfound/video-subtype-guids

to rebuild and reinstall it you will need to compile locally first using https://github.com/Andrey1994/screen_recorder_sdk/blob/master/cmake_build.cmd(you will need cmake and vs)
after that reinstall the python package from a local folder using commands like:

```
cd python
python -m pip install -U .
```
