### ISSUE TITLE
Project compilation failed on Cmake for creating environment

### ISSUE THREAD

**Issue by hash3liZer** [Andrey1994/screen_recorder_sdk#19]
Hi, 

I've been trying to compile the package from source but getting error regarding: `C:\Microsoft.Cpp.Default.props`. I've installed **CMAKE** and **Visual Studio 14 2015 x64** build tools. After moving to directory, i'm simply running the `cmake_build.cmd` file but no success. The command i ran: 

```
$ ./cmake_build.cmd
```

Error:

![image](https://user-images.githubusercontent.com/29171692/161423705-e43ed8b7-dc01-407c-88d6-4231485a4437.png)

**Comment by Andrey1994** [comment]
Provide full path instead ..
Or check how its build in CI

**Comment by hash3liZer** [comment]
NVM, the package i have installed of `Visual Studio 14 2015` wasn't complete. I tried with installing the complete version of studio with C++ development tools. It worked! Thanks.
