### ISSUE TITLE
helpme to get pid of firefox or chrome browser pid

### ISSUE THREAD

**Issue by vbpatel73** [Andrey1994/screen_recorder_sdk#2]
Hi, 
I got pid of browser instance which i passed but still getting below error. help me pls.
[2020-07-17 11:28:57.177] [recordLogger] [info] Created d3d11 device from 0
[2020-07-17 11:28:57.178] [recordLogger] [info] found 1 displays
[2020-07-17 11:28:57.182] [recordLogger] [error] Unable to find window for pid 21708
[2020-07-17 11:28:57.182] [recordLogger] [error] Unable to get process window

**Comment by Andrey1994** [comment]
Hi, I suppose pid you provided is wrong. Maybe for firefox/chrome there are multiple processes or window is not open...   you can also try pid 0 for full screen capture

**Comment by vbpatel73** [comment]
with pid 0 it is working perfect but how i can get active firefox pid to record only active one?

**Comment by Andrey1994** [comment]
I dont know, for some reason using chrome I see ~15 processes even if chrome is not running and I really have no idea how to determine which one refers to real window which you see on desktop...

Few ideas I have:

* try them all in a loop
* try to run chrome from your own script, smth like 
```
import subprocess

chrome = subprocess.Popen(['chrome.exe'])
print(chrome.pid)
```

**Comment by Andrey1994** [comment]
I think psutils allows you to get all running processes, so you are able to iterate, check names and try to run screen recorder
