### ISSUE TITLE
Could not init InitializeSinkWriter

### ISSUE THREAD

**Issue by AkashPatel21** [Andrey1994/screen_recorder_sdk#3]
Hello , i'm getting following error when i try to record something ,please help me with the following issue:
[2020-08-25 17:09:11.433] [recordLogger] [error] Could not init InitializeSinkWriter
[2020-08-25 17:09:11.435] [recordLogger] [error] MFEncoder is not null
[2020-08-25 17:09:11.438] [recordLogger] [error] Could not init InitializeSinkWriter
[2020-08-25 17:09:11.441] [recordLogger] [error] MFEncoder is not null
[2020-08-25 17:09:11.444] [recordLogger] [error] Could not init InitializeSinkWriter
[2020-08-25 17:09:11.450] [recordLogger] [error] MFEncoder is not null

**Comment by Andrey1994** [comment]
Hi.

Do you run it with admin privileges?(start cmd as administrator)

Which OS version do you use?

Could you share your code snippet?

And what about GPUs at your PC?

**Comment by Andrey1994** [comment]
Also try False as the last argument in start_video_recording method

**Comment by AkashPatel21** [comment]
Thanks for quick response , found the cause , the file wasn't getting initialize properly due to admin privileges.

**Comment by abrichr** [comment]
We are experiencing the same error:

- Windows 11 (emulated with UTM on MacOS 14.2.1)
- cmd with admin privileges
- with `use_hw_transfowrms=False`
- Apple M2 Max GPU

Code is at https://github.com/OpenAdaptAI/OpenAdapt/blob/main/openadapt/capture/_windows.py

@AkashPatel21 can you please clarify what steps you took to resolve the error?

@Andrey1994 any ideas would be appreciated 🙏 

Edit: latest code at https://github.com/OpenAdaptAI/OpenAdapt/blob/cff873e2b9a887f6df5b3c8475177b4d3983cad1/openadapt/capture/_windows.py

**Comment by Andrey1994** [comment]
I have no ideas how it works in such setup and have no Mac to give it a try

**Comment by Cody-DV** [comment]
@Andrey1994 thank you for the quick reply.

We have re-tested this on a Windows 10 machine Intel UHD 620 graphics, with the same results.

**Comment by abrichr** [comment]
@Andrey1994 thank you for the quick reply.

We have re-tested this on a Windows 10 Huawei Matebook W-29 that automatically switches between Intel UHD 620 and NVIDIA Geforce MX150 graphics, with the same results. However on the same machine the demo code at https://screen-recorder-sdk.readthedocs.io/en/latest/Examples.html#python-basic-demo works.

Edit: it appears UTM does not support DirectX: https://github.com/utmapp/UTM/discussions/5058
