### ISSUE TITLE
Capturing the screen by selecting which monitor to capture screen from and not the PID

### ISSUE THREAD

**Issue by KhalidYahia94** [Andrey1994/screen_recorder_sdk#4]
Is there any method to select which monitor to capture the screen from? because using only PID produces some limitations and setting its value to 0 to capture the main monitor is also not so functional when having more than one monitor.

**Comment by Andrey1994** [comment]
When you provide pid of process to capture it will find monitor based on it. Which limitations in this approach do you see?  I can add this option easily if needed

**Comment by KhalidYahia94** [comment]
I want to have the ability to just simply choose capture video from montior one or two for example, without giving a pid.

**Comment by Andrey1994** [comment]
I will add this option

**Comment by Andrey1994** [comment]
Implemented in new release, check docs and updated sample for instructions https://screen-recorder-sdk.readthedocs.io/en/latest/Examples.html#python-basic-demo
